CREATE TABLE IF NOT EXISTS "Posts" ("id"   SERIAL , "post" VARCHAR(512), "mediaUrl" VARCHAR(255), "userId" INTEGER, "usersRead" INTEGER[], "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "Users" ("id"   SERIAL , "userName" VARCHAR(255), "email" VARCHAR(255) UNIQUE, "password" VARCHAR(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
